apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: gitlab
spec:
  ports:
    - port: 5432
  selector:
    app: gitlab
    tier: postgreSQL
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
  labels:
    app: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgresql
  labels:
    app: gitlab
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitlab
        tier: postgreSQL
    spec:
      containers:
      - image: docker.io/tomcli/postgres:latest
        name: postgresql
        env:
          - name: GITLAB_DB_USER
            value : git
          - name: GITLAB_DB_NAME
            value : gitlabhq_production
        ports:
        - containerPort: 5432
          name: postgresql
        volumeMounts:
        - name: postgresql
          mountPath: /var/lib/postgresql:rw
      volumes:
      - name: postgresql
        persistentVolumeClaim:
          claimName: postgres-claim
