apiVersion: v1
data:
  proxy-connect-timeout: "15"
  proxy-read-timeout: "600"
  proxy-send-timeout: "600"
  hsts-include-subdomains: "false"
  proxy-body-size: "1024m"
  server-name-hash-bucket-size: "256"
  enable-vts-status: "true"
kind: ConfigMap
metadata:
  namespace: nginx-ingress
  name: nginx
