set -e

GITLAB_DB_USER=${GITLAB_DB_USER:-git}
GITLAB_DB_NAME=${GITLAB_DB_NAME:-gitlabhq_production}

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -d template1 <<-EOSQL
    CREATE EXTENSION IF NOT EXISTS pg_trgm;
    CREATE USER "$GITLAB_DB_USER" CREATEDB;
    CREATE DATABASE "$GITLAB_DB_NAME" OWNER "$GITLAB_DB_USER";
    GRANT ALL PRIVILEGES ON DATABASE "$GITLAB_DB_NAME" TO "$GITLAB_DB_USER";
EOSQL
